
*----- Global for ALL indicators

#delimit ;
global a2j " 
had_dispute
ndisputes
land neighbors housing family injury citizenship gov public_services products services MoneyDebt employment
access2info
access2rep 
AJD_adviser_1_bin AJD_adviser_2_bin AJD_adviser_3_bin AJD_adviser_4_bin AJD_adviser_5_bin AJD_adviser_6_bin AJD_adviser_7_bin AJD_adviser_8_bin AJD_adviser_9_bin AJD_adviser_10_bin AJD_adviser_11_bin AJD_adviser_12_bin AJD_adviser_13_bin AJD_adviser_14_bin AJD_adviser_15_bin AJD_adviser_16_bin AJD_adviser_17_bin

adviser_help_1 adviser_help_2 adviser_help_3 adviser_help_4 adviser_help_5 adviser_help_6 adviser_help_7 adviser_help_8 adviser_help_9 adviser_help_10 adviser_help_11 adviser_help_12 adviser_help_13 adviser_help_14 adviser_help_15 adviser_help_16 adviser_help_17

AJD_noadvice_reason_1 AJD_noadvice_reason_2 AJD_noadvice_reason_3 AJD_noadvice_reason_4 AJD_noadvice_reason_5 AJD_noadvice_reason_6 AJD_noadvice_reason_7 AJD_noadvice_reason_8 AJD_noadvice_reason_9 AJD_noadvice_reason_10 AJD_noadvice_reason_11 AJD_noadvice_reason_12 AJD_noadvice_reason_13 AJD_noadvice_reason_14 AJD_noadvice_reason_15 AJD_noadvice_reason_16 AJD_noadvice_reason_17

AJR_action_1 AJR_action_2 AJR_action_3 AJR_action_4
AJR_noaction_1 AJR_noaction_2 AJR_noaction_3 AJR_noaction_4 AJR_noaction_5 AJR_noaction_6 AJR_noaction_7 AJR_noaction_8 AJR_noaction_9 AJR_noaction_10 AJR_noaction_11 AJR_noaction_12 AJR_noaction_13
access2drm
drm_1 drm_2 drm_3 drm_4 drm_5 drm_6 drm_7 drm_8 drm_9 drm_10 drm_11
AJR_noresol_reason_1 AJR_noresol_reason_2 AJR_noresol_reason_3 AJR_noresol_reason_4 AJR_noresol_reason_5 AJR_noresol_reason_6 AJR_noresol_reason_7 AJR_noresol_reason_8 AJR_noresol_reason_9 AJR_noresol_reason_10 AJR_noresol_reason_11 AJR_noresol_reason_12 AJR_noresol_reason_13 AJR_noresol_reason_14 AJR_noresol_reason_15 AJR_noresol_reason_16

drm_1_eff drm_2_eff drm_3_eff drm_4_eff drm_5_eff drm_6_eff drm_7_eff drm_8_eff drm_9_eff drm_11_eff 
drm_1_fair drm_2_fair drm_3_fair drm_4_fair drm_5_fair drm_6_fair drm_7_fair drm_8_fair drm_9_fair drm_11_fair 
drm_1_aff drm_2_aff drm_3_aff drm_4_aff drm_5_aff drm_6_aff drm_7_aff drm_8_aff drm_9_aff drm_11_aff 
drm_1_dur drm_2_dur drm_3_dur drm_4_dur drm_5_dur drm_6_dur drm_7_dur drm_8_dur drm_9_dur drm_11_dur 
drm_1_help drm_2_help drm_3_help drm_4_help drm_5_help drm_6_help drm_7_help drm_8_help drm_9_help drm_11_help

drm_res_1_outcome drm_res_2_outcome drm_res_3_outcome drm_res_4_outcome drm_res_5_outcome drm_res_6_outcome drm_res_7_outcome drm_res_8_outcome drm_res_9_outcome drm_res_11_outcome 
drm_res_1_ap drm_res_2_ap drm_res_3_ap drm_res_4_ap drm_res_5_ap drm_res_6_ap drm_res_7_ap drm_res_8_ap drm_res_9_ap drm_res_11_ap drm_res_1_rep drm_res_2_rep drm_res_3_rep drm_res_4_rep drm_res_5_rep drm_res_6_rep drm_res_7_rep drm_res_8_rep drm_res_9_rep drm_res_11_rep 
drm_res_1_oth drm_res_2_oth drm_res_3_oth drm_res_4_oth drm_res_5_oth drm_res_6_oth drm_res_7_oth drm_res_8_oth drm_res_9_oth drm_res_11_oth

AJR_settle_resol_1 AJR_settle_resol_2 AJR_settle_resol_3 AJR_settle_resol_4 AJR_settle_resol_5 AJR_settle_resol_6 AJR_settle_resol_7 AJR_settle_resol_8 AJR_settle_resol_9 AJR_settle_resol_10 AJR_settle_resol_11

diff_months timeliness 
fair_process outcome_1 outcome_2 outcome_3 outcome_done
had_hardship
hardship_1 hardship_2 hardship_3 hardship_4 hardship_5 hardship_6 hardship_7 hardship_8 hardship_9 hardship_10 hardship_11 hardship_12 hardship_13 hardship_14 hardship_15 hardship_16
legal_rights infosource expert_help fair_outcome
" ;
;
#delimit cr



*----- Create vars for sample sizes
foreach v in $a2j {
	g `v'_n = `v'
}

*----- Global for ALL counts

global a2j_n "had_dispute_n ndisputes_n land_n neighbors_n housing_n family_n injury_n citizenship_n gov_n public_services_n products_n services_n MoneyDebt_n employment_n access2info_n access2rep_n AJD_adviser_1_bin_n AJD_adviser_2_bin_n AJD_adviser_3_bin_n AJD_adviser_4_bin_n AJD_adviser_5_bin_n AJD_adviser_6_bin_n AJD_adviser_7_bin_n AJD_adviser_8_bin_n AJD_adviser_9_bin_n AJD_adviser_10_bin_n AJD_adviser_11_bin_n AJD_adviser_12_bin_n AJD_adviser_13_bin_n AJD_adviser_14_bin_n AJD_adviser_15_bin_n AJD_adviser_16_bin_n AJD_adviser_17_bin_n adviser_help_1_n adviser_help_2_n adviser_help_3_n adviser_help_4_n adviser_help_5_n adviser_help_6_n adviser_help_7_n adviser_help_8_n adviser_help_9_n adviser_help_10_n adviser_help_11_n adviser_help_12_n adviser_help_13_n adviser_help_14_n adviser_help_15_n adviser_help_16_n adviser_help_17_n AJD_noadvice_reason_1_n AJD_noadvice_reason_2_n AJD_noadvice_reason_3_n AJD_noadvice_reason_4_n AJD_noadvice_reason_5_n AJD_noadvice_reason_6_n AJD_noadvice_reason_7_n AJD_noadvice_reason_8_n AJD_noadvice_reason_9_n AJD_noadvice_reason_10_n AJD_noadvice_reason_11_n AJD_noadvice_reason_12_n AJD_noadvice_reason_13_n AJD_noadvice_reason_14_n AJD_noadvice_reason_15_n AJD_noadvice_reason_16_n AJD_noadvice_reason_17_n AJR_action_1_n AJR_action_2_n AJR_action_3_n AJR_action_4_n AJR_noaction_1_n AJR_noaction_2_n AJR_noaction_3_n AJR_noaction_4_n AJR_noaction_5_n AJR_noaction_6_n AJR_noaction_7_n AJR_noaction_8_n AJR_noaction_9_n AJR_noaction_10_n AJR_noaction_11_n AJR_noaction_12_n AJR_noaction_13_n access2drm_n drm_1_n drm_2_n drm_3_n drm_4_n drm_5_n drm_6_n drm_7_n drm_8_n drm_9_n drm_10_n drm_11_n AJR_noresol_reason_1_n AJR_noresol_reason_2_n AJR_noresol_reason_3_n AJR_noresol_reason_4_n AJR_noresol_reason_5_n AJR_noresol_reason_6_n AJR_noresol_reason_7_n AJR_noresol_reason_8_n AJR_noresol_reason_9_n AJR_noresol_reason_10_n AJR_noresol_reason_11_n AJR_noresol_reason_12_n AJR_noresol_reason_13_n AJR_noresol_reason_14_n AJR_noresol_reason_15_n AJR_noresol_reason_16_n drm_1_eff_n drm_2_eff_n drm_3_eff_n drm_4_eff_n drm_5_eff_n drm_6_eff_n drm_7_eff_n drm_8_eff_n drm_9_eff_n drm_11_eff_n drm_1_fair_n drm_2_fair_n drm_3_fair_n drm_4_fair_n drm_5_fair_n drm_6_fair_n drm_7_fair_n drm_8_fair_n drm_9_fair_n drm_11_fair_n drm_1_aff_n drm_2_aff_n drm_3_aff_n drm_4_aff_n drm_5_aff_n drm_6_aff_n drm_7_aff_n drm_8_aff_n drm_9_aff_n drm_11_aff_n drm_1_dur_n drm_2_dur_n drm_3_dur_n drm_4_dur_n drm_5_dur_n drm_6_dur_n drm_7_dur_n drm_8_dur_n drm_9_dur_n drm_11_dur_n drm_1_help_n drm_2_help_n drm_3_help_n drm_4_help_n drm_5_help_n drm_6_help_n drm_7_help_n drm_8_help_n drm_9_help_n drm_11_help_n drm_res_1_outcome_n drm_res_2_outcome_n drm_res_3_outcome_n drm_res_4_outcome_n drm_res_5_outcome_n drm_res_6_outcome_n drm_res_7_outcome_n drm_res_8_outcome_n drm_res_9_outcome_n drm_res_11_outcome_n drm_res_1_ap_n drm_res_2_ap_n drm_res_3_ap_n drm_res_4_ap_n drm_res_5_ap_n drm_res_6_ap_n drm_res_7_ap_n drm_res_8_ap_n drm_res_9_ap_n drm_res_11_ap_n drm_res_1_rep_n drm_res_2_rep_n drm_res_3_rep_n drm_res_4_rep_n drm_res_5_rep_n drm_res_6_rep_n drm_res_7_rep_n drm_res_8_rep_n drm_res_9_rep_n drm_res_11_rep_n drm_res_1_oth_n drm_res_2_oth_n drm_res_3_oth_n drm_res_4_oth_n drm_res_5_oth_n drm_res_6_oth_n drm_res_7_oth_n drm_res_8_oth_n drm_res_9_oth_n drm_res_11_oth_n AJR_settle_resol_1_n AJR_settle_resol_2_n AJR_settle_resol_3_n AJR_settle_resol_4_n AJR_settle_resol_5_n AJR_settle_resol_6_n AJR_settle_resol_7_n AJR_settle_resol_8_n AJR_settle_resol_9_n AJR_settle_resol_10_n AJR_settle_resol_11_n diff_months_n timeliness_n fair_process_n outcome_1_n outcome_2_n outcome_3_n outcome_done_n had_hardship_n hardship_1_n hardship_2_n hardship_3_n hardship_4_n hardship_5_n hardship_6_n hardship_7_n hardship_8_n hardship_9_n hardship_10_n hardship_11_n hardship_12_n hardship_13_n hardship_14_n hardship_15_n hardship_16_n legal_rights_n infosource_n expert_help_n fair_outcome_n"

