label var had_dispute "Prevalence"
label var ndisputes "Co-occurrence"

label var land "Problem category - land"
label var neighbors "Problem category - neighbors"
label var housing "Problem category - housing"
label var family "Problem category - family"
label var injury "Problem category - injury"
label var citizenship "Problem category - citizenship"
label var gov "Problem category - gov"
label var public_services "Problem category - public_services"
label var products "Problem category - products"
label var services "Problem category - services"
label var MoneyDebt "Problem category - MoneyDebt"
label var employment "Problem category - employment"

label var access2info "Access to information"

label var access2rep "Access to representation"

label var AJD_adviser_1_bin "A court (small claims court, District Court, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var AJD_adviser_2_bin "A tribunal (e.g. International Protection Appeals Tribunal, Workplace Relations Commission, Social Welfare Appeals Office,"
label var AJD_adviser_3_bin "An Ombudsman (e.g. Financial Services Ombudsman)"
label var AJD_adviser_4_bin "The Gardai/police (or other law-enforcement)"
label var AJD_adviser_5_bin "Family Mediation Service"
label var AJD_adviser_6_bin "Another mediation, conciliation or other complaint or dispute resolution service (including online or commercial services)"
label var AJD_adviser_7_bin "A private solicitor or person working in a solicitor's office"
label var AJD_adviser_8_bin "A private barrister or person working in a barrister's office"
label var AJD_adviser_9_bin "A Legal Aid Board Law Centre"
label var AJD_adviser_10_bin "Another law centre such as the Free Legal Advice Centres"
label var AJD_adviser_11_bin "A government department, local council or government agency (e.g. a Housing or Social Welfare officer)"
label var AJD_adviser_12_bin "A non-legal professional, organisation or help line (e.g. Citizens Information Centre, Citizens Information Phone Centre,"
label var AJD_adviser_13_bin "Other person of standing in the local community (e.g. a politician, teacher, councillor, TDs or senator)"
label var AJD_adviser_14_bin "Online search (e.g. Google)"
label var AJD_adviser_15_bin "Social media (e.g. Facebook, X, Tik Tok, Reddit, Quora, Instagram)"
label var AJD_adviser_16_bin "AI tools (e.g. ChatGPT, Gemini or other ChatBot)"
label var AJD_adviser_17_bin "Another person (e.g. a friend, family member, or acquaintance [not a professional])"


label var adviser_help_1 "Helpfulness - A court (small claims court, District Court, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var adviser_help_2 "Helpfulness - A tribunal (e.g. International Protection Appeals Tribunal, Workplace Relations Commission, Social Welfare Appeals Office,"
label var adviser_help_3 "Helpfulness - An Ombudsman (e.g. Financial Services Ombudsman)"
label var adviser_help_4 "Helpfulness - The Gardai/police (or other law-enforcement)"
label var adviser_help_5 "Helpfulness - Family Mediation Service"
label var adviser_help_6 "Helpfulness - Another mediation, conciliation or other complaint or dispute resolution service (including online or commercial services)"
label var adviser_help_7 "Helpfulness - A private solicitor or person working in a solicitor's office"
label var adviser_help_8 "Helpfulness - A private barrister or person working in a barrister's office"
label var adviser_help_9 "Helpfulness - A Legal Aid Board Law Centre"
label var adviser_help_10 "Helpfulness - Another law centre such as the Free Legal Advice Centres"
label var adviser_help_11 "Helpfulness - A government department, local council or government agency (e.g. a Housing or Social Welfare officer)"
label var adviser_help_12 "Helpfulness - A non-legal professional, organisation or help line (e.g. Citizens Information Centre, Citizens Information Phone Centre,"
label var adviser_help_13 "Helpfulness - Other person of standing in the local community (e.g. a politician, teacher, councillor, TDs or senator)"
label var adviser_help_14 "Helpfulness - Online search (e.g. Google)"
label var adviser_help_15 "Helpfulness - Social media (e.g. Facebook, X, Tik Tok, Reddit, Quora, Instagram)"
label var adviser_help_16 "Helpfulness - AI tools (e.g. ChatGPT, Gemini or other ChatBot)"
label var adviser_help_17 "Helpfulness - Another person (e.g. a friend, family member, or acquaintance [not a professional])"


label var AJD_noadvice_reason_1 "There was no real disagreement or problem"
label var AJD_noadvice_reason_2 "I felt the other person or organisation was in the right"
label var AJD_noadvice_reason_3 "The issue resolved itself without needing help"
label var AJD_noadvice_reason_4 "I got all the help I needed from other organisations/people"
label var AJD_noadvice_reason_5 "I didn't feel I needed help"
label var AJD_noadvice_reason_6 "I didn't think the issue was serious enough"
label var AJD_noadvice_reason_7 "I was concerned about how much time it would take"
label var AJD_noadvice_reason_8 "I was concerned about how much it would cost"
label var AJD_noadvice_reason_9 "It was difficult to find someone nearby who could help me"
label var AJD_noadvice_reason_10 "I thought it would be too stressful"
label var AJD_noadvice_reason_11 "I was afraid it would damage my relationship with the other person or organisation"
label var AJD_noadvice_reason_12 "I was scared to take action or ask for help"
label var AJD_noadvice_reason_13 "I didn't know where or how to find information or advice"
label var AJD_noadvice_reason_14 "I didn't think it would change the outcome"
label var AJD_noadvice_reason_15 "I had tried seeking help before and it wasn't helpful"
label var AJD_noadvice_reason_16 "Someone told me not to get advice or information"
label var AJD_noadvice_reason_17 "Other reason"


label var AJR_action_1 "Haven't done / I didn't do anything and don't expect to"
label var AJR_action_2 "Nothing yet but expect to"
label var AJR_action_3 "Have done something (please specify briefly)"
label var AJR_action_4 "No, as it has resolved itself or is no longer an issue"


label var AJR_noaction_1 "It wasn't very important"
label var AJR_noaction_2 "It was resolved quickly"
label var AJR_noaction_3 "It would take too long"
label var AJR_noaction_4 "It would be too stressful"
label var AJR_noaction_5 "It would cost too much"
label var AJR_noaction_6 "It would damage the relationship with the other side"
label var AJR_noaction_7 "It would make you uncomfortable/ you were too ashamed or embarrassed to ask for help"
label var AJR_noaction_8 "It would make no difference"
label var AJR_noaction_9 "You had bigger issues"
label var AJR_noaction_10 "You were at fault or there was no dispute"
label var AJR_noaction_11 "You didn't know what to do"
label var AJR_noaction_12 "You didn't need information or advice"
label var AJR_noaction_13 "Other reason"

label var access2drm "Access to DRM (SDG 16.3.3)"


label var drm_1 "A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_2 "A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_3 "An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_4 "The Gardai/police (or other law-enforcement)"
label var drm_5 "A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_6 "A lawyer, or person working in a lawyer's office"
label var drm_7 "A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_8 "A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_9 "Other dispute resolution service, including online and commercial services"
label var drm_10 "Other person (e.g. a friend, family member, or acquaintance not in a professional capacity)"
label var drm_11 "Other professional or organisation"


label var AJR_noresol_reason_1 "The issue is/was not important enough"
label var AJR_noresol_reason_2 "The issue resolved so I didn't need to"
label var AJR_noresol_reason_3 "I was/am confident that I could/can easily resolve it by myself"
label var AJR_noresol_reason_4 "I was/am confident that I could/can easily resolve it with the help I got/am getting"
label var AJR_noresol_reason_5 "Up to the other party to take this action"
label var AJR_noresol_reason_6 "I caused the issue"
label var AJR_noresol_reason_7 "I did not know where to go"
label var AJR_noresol_reason_8 "I could not obtain legal assistance"
label var AJR_noresol_reason_9 "It was too expensive / I was fearful of what it could cost"
label var AJR_noresol_reason_10 "It was too far away or hard to reach"
label var AJR_noresol_reason_11 "It was too inconvenient"
label var AJR_noresol_reason_12 "I did not trust the authorities"
label var AJR_noresol_reason_13 "I did not think they could help"
label var AJR_noresol_reason_14 "I was afraid of the consequences for me/my family"
label var AJR_noresol_reason_15 "I did not know it was possible to turn somewhere to resolve the issue"
label var AJR_noresol_reason_16 "Other reason"


label var drm_1_eff "Efficiency - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_2_eff "Efficiency - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_3_eff "Efficiency - An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_4_eff "Efficiency - The Gardai/police (or other law-enforcement)"
label var drm_5_eff "Efficiency - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_6_eff "Efficiency - A lawyer, or person working in a lawyer's office"
label var drm_7_eff "Efficiency - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_8_eff "Efficiency - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_9_eff "Efficiency - Other dispute resolution service, including online and commercial services"
label var drm_11_eff "Efficiency - Other professional or organisation"


label var drm_1_fair "Fairness - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_1_fair "Fairness - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_3_fair "Fairness - An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_4_fair "Fairness - The Gardai/police (or other law-enforcement)"
label var drm_5_fair "Fairness - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_6_fair "Fairness - A lawyer, or person working in a lawyer's office"
label var drm_7_fair "Fairness - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_8_fair "Fairness - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_9_fair "Fairness - Other dispute resolution service, including online and commercial services"
label var drm_11_fair "Fairness - Other professional or organisation"


label var drm_1_aff "Affordability - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_2_aff "Affordability - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_3_aff "Affordability - An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_4_aff "Affordability - The Gardai/police (or other law-enforcement)"
label var drm_5_aff "Affordability - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_6_aff "Affordability - A lawyer, or person working in a lawyer's office"
label var drm_7_aff "Affordability - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_8_aff "Affordability - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_9_aff "Affordability - Other dispute resolution service, including online and commercial services"
label var drm_11_aff "Affordability - Other professional or organisation"


label var drm_1_dur "Duration - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_2_dur "Duration - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_3_dur "Duration - An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_4_dur "Duration - The Gardai/police (or other law-enforcement)"
label var drm_5_dur "Duration - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_6_dur "Duration - A lawyer, or person working in a lawyer's office"
label var drm_7_dur "Duration - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_8_dur "Duration - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_9_dur "Duration - Other dispute resolution service, including online and commercial services"
label var drm_11_dur "Duration - Other professional or organisation"


label var drm_1_help "Helpfulness - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_2_help "Helpfulness - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_3_help "Helpfulness - An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_4_help "Helpfulness - The Gardai/police (or other law-enforcement)"
label var drm_5_help "Helpfulness - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_6_help "Helpfulness - A lawyer, or person working in a lawyer's office"
label var drm_7_help "Helpfulness - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_8_help "Helpfulness - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_9_help "Helpfulness - Other dispute resolution service, including online and commercial services"
label var drm_11_help "Helpfulness - Other professional or organisation"


label var drm_res_1_outcome "Written outcome - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_res_2_outcome "Written outcome - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_res_3_outcome "Written outcome - An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_res_4_outcome "Written outcome - The Gardai/police (or other law-enforcement)"
label var drm_res_5_outcome "Written outcome - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_res_6_outcome "Written outcome - A lawyer, or person working in a lawyer's office"
label var drm_res_7_outcome "Written outcome - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_res_8_outcome "Written outcome - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_res_9_outcome "Written outcome - Other dispute resolution service, including online and commercial services"
label var drm_res_11_outcome "Written outcome - Other professional or organisation"


label var drm_res_1_ap "Appeal rights - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_res_2_ap "Appeal rights - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_res_3_ap "Appeal rights - An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_res_4_ap "Appeal rights - The Gardai/police (or other law-enforcement)"
label var drm_res_5_ap "Appeal rights - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_res_6_ap "Appeal rights - A lawyer, or person working in a lawyer's office"
label var drm_res_7_ap "Appeal rights - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_res_8_ap "Appeal rights - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_res_9_ap "Appeal rights - Other dispute resolution service, including online and commercial services"
label var drm_res_11_ap "Appeal rights - Other professional or organisation"


label var drm_res_1_rep "Lawyer representation - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_res_2_rep "Lawyer representation - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_res_3_rep "Lawyer representation - An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_res_4_rep "Lawyer representation - The Gardai/police (or other law-enforcement)"
label var drm_res_5_rep "Lawyer representation - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_res_6_rep "Lawyer representation - A lawyer, or person working in a lawyer's office"
label var drm_res_7_rep "Lawyer representation - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_res_8_rep "Lawyer representation - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_res_9_rep "Lawyer representation - Other dispute resolution service, including online and commercial services"
label var drm_res_11_rep "Lawyer representation - Other professional or organisation"


label var drm_res_1_oth "Other representation - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var drm_res_2_oth "Other representation - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var drm_res_3_oth "Other representation - An Ombudsman (e.g. Financial Services Ombudsman)"
label var drm_res_4_oth "Other representation - The Gardai/police (or other law-enforcement)"
label var drm_res_5_oth "Other representation - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var drm_res_6_oth "Other representation - A lawyer, or person working in a lawyer's office"
label var drm_res_7_oth "Other representation - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var drm_res_8_oth "Other representation - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var drm_res_9_oth "Other representation - Other dispute resolution service, including online and commercial services"
label var drm_res_11_oth "Other representation - Other professional or organisation"


label var AJR_settle_resol_1 "Resolution - A court judgment"
label var AJR_settle_resol_2 "Resolution - A tribunal decision"
label var AJR_settle_resol_3 "Resolution - A decision or direction by another type of authority (e.g. Ombudsman, Gardai, government agency, local authority)"
label var AJR_settle_resol_4 "Resolution - As a result of another type of mediation, conciliation or other dispute resolution, including using a complaints process"
label var AJR_settle_resol_5 "Resolution - Following exchanges between lawyers acting on behalf of one or more parties"
label var AJR_settle_resol_6 "Resolution - Following the intervention of a third person (e.g. a community leader)"
label var AJR_settle_resol_7 "Resolution - I reached an agreement without any assistance of a lawyer or third person"
label var AJR_settle_resol_8 "Resolution - I got what I wanted without having to do anything"
label var AJR_settle_resol_9 "Resolution - I made changes to avoid the issue (e.g. changed job, housing)"
label var AJR_settle_resol_10 "Resolution - I gave up trying to do anything and nothing further happened"
label var AJR_settle_resol_11 "Resolution - Some other way. Please describe how."


label var diff_months "Average duration in months"
label var timeliness "Overall timeliness"
label var fair_process "Overall procedural fairness"

label var outcome_1 "Status - Ongoing/too early to say"
label var outcome_2 "Status - Done with, issue persists, but all have given up trying to resolve it further"
label var outcome_3 "Status - Done with, issue resolved"
label var outcome_done "Status - Done (all)"

label var had_hardship "Incidence of hardship"

label var hardship_1 "Hardship - Health difficulties or injury"
label var hardship_2 "Hardship - Stress or emotional strain"
label var hardship_3 "Hardship - Damage to personal or family relationships"
label var hardship_4 "Hardship - Being threatened or feeling unsafe"
label var hardship_5 "Hardship - Damage to property"
label var hardship_6 "Hardship - Changes to your housing situation"
label var hardship_7 "Hardship - Loss of employment"
label var hardship_8 "Hardship - Loss of money"
label var hardship_9 "Hardship - Loss of confidence or fear"
label var hardship_10 "Hardship - Deterioration in mental health (e.g. anxiety, depression)"
label var hardship_11 "Hardship - Feeling isolated or loss of support networks"
label var hardship_12 "Hardship - Use of addictive substances (e.g. alcohol or drugs)"
label var hardship_13 "Hardship - Delay or disruption to education or training"
label var hardship_14 "Hardship - Delay or disruption in accessing public services (e.g. healthcare, social services)"
label var hardship_15 "Hardship - Finding everyday activities more difficult"
label var hardship_16 "Hardship - Feeling less trust in public institutions (e.g. justice system, police, government)"


label var legal_rights "People know their legal rights and responsibilities"
label var infosource "People know where to get good information and advice"
label var expert_help "People were able to get all the expert help they needed"
label var fair_outcome "People were confident they could achieve a fair outcome"

