/*=================================================================================================================
Project:		OECD - LNS Ireland
Routine:		Variable labels
Author(s):		Natalia Rodriguez 	(nrodriguez@worldjusticeproject.org)
Dependencies:  	World Justice Project
Creation Date:	October, 2025

Description:
Do-file that creates and labels all variables

=================================================================================================================*/


label var respondentid "Respondent ID"
label var q11 "Q11. Gender. Do you identify as:"
label var q03 "Q3. Age"
label var q18 "Q18. Which of the following is the highest level of education or training you have completed?"
label var education "Education"
label var q17 "Q17. Which one of the following best describes your current situation?"
label var employment "Employment"
label var qsocialgrade "QSocialGrade. Please indicate which occupational group best describes the main earner in your household, or which group fits best."
label var socialgrade "Social Grade"
label var county "County. What is the name of the county where you currently live?"
label var region "Region."
label var q23_1_1 "Q23_1. Are you currently or previously have been in the past two years...? - A tenant"
label var q23_1_2 "Q23_1. Are you currently or previously have been in the past two years...? - A landlord"
label var q23_1_3 "Q23_1. Are you currently or previously have been in the past two years...? - A home-owner"
label var q23_2_01_1 "Q23_2_1_1. Issues experienced - Including issues with buying or selling property and disputes over title or ownership boundary locations and rights of way and Land Registry matters"
label var q23_2_02_1 "Q23_2_2_1. Issues experienced - Disputes about maintenance including of boundaries trees gardens"
label var q23_2_02_2 "Q23_2_2_2. Issues experienced - Problems or disputes to do with noise animals or unpleasant behaviour"
label var q23_2_02_3 "Q23_2_2_3. Issues experienced - Other disputes with neighbours such as issues with parking"
label var q23_2_03_1 "Q23_2_3_1. Issues experienced - Problems or disputes with your landlord over your rent or return of deposit"
label var q23_2_03_2 "Q23_2_3_2. Issues experienced - Problem with your landlord about the condition of your accommodation including damage/repairs"
label var q23_2_03_3 "Q23_2_3_3. Issues experienced - Eviction or threats of eviction or other harassment by a landlord"
label var q23_2_04_1 "Q23_2_4_1. Issues experienced - Issues with a tenant such as delayed/no payment of rent or dispute over a deposit"
label var q23_2_04_2 "Q23_2_4_2. Issues experienced - Property-related issues such as damage by tenants or access to property"
label var q23_2_04_3 "Q23_2_4_3. Issues experienced - Issues with tenants such as evictions or complaints"
label var q23_2_05_1 "Q23_2_5_1. Issues experienced - Building/planning related disputes"
label var q23_2_05_2 "Q23_2_5_2. Issues experienced - Issues with builders/tradespeople about the quality of construction or repairs or disputes about costs"
label var q23_2_05_3 "Q23_2_5_3. Issues experienced - Disputes about communal repairs/maintenance/costs"
label var q23_2_05_4 "Q23_2_5_4. Issues experienced - Problems or disputes concerning Local Property Tax or Council/local services"
label var q23_2_05_5 "Q23_2_5_5. Issues experienced - Squatters"
label var q23_2_05_6 "Q23_2_5_6. Issues experienced - Dispute with utilities/essential services (e.g. waste disposal water electricity internet or other utility provider)"
label var q23_2_05_7 "Q23_2_5_7. Issues experienced - Mortgage related issues including repossession threatened repossession or late payment"
label var q23_2_06_1 "Q23_2_6_1. Issues experienced - Separation and/or divorce"
label var q23_2_06_2 "Q23_2_6_2. Issues experienced - Violent or controlling behaviour by a current or former partner"
label var q23_2_06_3 "Q23_2_6_3. Issues experienced - Violent or controlling behaviour by another family member"
label var q23_2_06_4 "Q23_2_6_4. Issues experienced - Issues related to child access custody or child/spousal maintenance"
label var q23_2_06_5 "Q23_2_6_5. Issues experienced - Problems or disputes related to elderly or other dependent adult care"
label var q23_2_06_6 "Q23_2_6_6. Issues experienced - Disputes related to inheritance or a will"
label var q23_2_07_1 "Q23_2_7_1. Issues experienced - Issues obtaining or with an Irish visa or residence card renewal"
label var q23_2_07_2 "Q23_2_7_2. Issues experienced - Issues seeking international protection subsidiary protection or permission to remain"
label var q23_2_07_3 "Q23_2_7_3. Issues experienced - Issues with an overseas visa / EU residence / emigration"
label var q23_2_07_4 "Q23_2_7_4. Issues experienced - Issues applying for Irish naturalisation/citizenship"
label var q23_2_07_5 "Q23_2_7_5. Issues experienced - Other citizenship or migration related issue"
label var q23_2_08_1 "Q23_2_8_1. Issues experienced - A road traffic accident in which you were injured caused or made worse by someone else"
label var q23_2_08_2 "Q23_2_8_2. Issues experienced - A road traffic accident in which someone else was injured that you caused or made worse"
label var q23_2_08_3 "Q23_2_8_3. Issues experienced - Work-related accident"
label var q23_2_08_4 "Q23_2_8_4. Issues experienced - Wrong or negligent medical treatment"
label var q23_2_08_5 "Q23_2_8_5. Issues experienced - Other injury or illness caused or worsened by someone else"
label var q23_2_09_1 "Q23_2_9_1. Issues experienced - Issues with jobseekers benefit or jobseekers allowance"
label var q23_2_09_2 "Q23_2_9_2. Issues experienced - Issues related to maternity/parental government benefit"
label var q23_2_09_3 "Q23_2_9_3. Issues experienced - Issues related to the State pension"
label var q23_2_09_4 "Q23_2_9_4. Issues experienced - Issues with education-related grants (e.g. student grant scheme)"
label var q23_2_09_5 "Q23_2_9_5. Issues experienced - Issues with Disability Allowance"
label var q23_2_09_6 "Q23_2_9_6. Issues experienced - Other government benefit/payment issues"
label var q23_2_10_1 "Q23_2_10_1. Issues experienced - Issues obtaining an Irish Passport other ID licences or other official documents"
label var q23_2_10_2 "Q23_2_10_2. Issues experienced - Issues with obtaining healthcare or disability services"
label var q23_2_10_3 "Q23_2_10_3. Issues experienced - Issues with obtaining government/social housing (excluding issues experienced as a tenant)"
label var q23_2_10_4 "Q23_2_10_4. Issues experienced - Issues with obtaining education"
label var q23_2_11_1 "Q23_2_11_1. Issues experienced - Product/purchases not delivered or significantly delayed"
label var q23_2_11_2 "Q23_2_11_2. Issues experienced - Difficulty getting refunds repairs or replacements for products that were faulty damaged or not as described"
label var q23_2_12_1 "Q23_2_12_1. Issues experienced - Issues with over-charging or hidden or unexpected fees"
label var q23_2_12_2 "Q23_2_12_2. Issues experienced - Issues with quality of services or other service-related disputes"
label var q23_2_13_1 "Q23_2_13_1. Issues experienced - Unable to pay bills/loans/debts including buy-now-pay-later (excluding mortgage and rental payments)"
label var q23_2_13_2 "Q23_2_13_2. Issues experienced - Disputes about insurance coverage/claim"
label var q23_2_13_3 "Q23_2_13_3. Issues experienced - Disputes with the bank or other financial institutions including refusal of credit/loan/mortgage"
label var q23_2_13_4 "Q23_2_13_4. Issues experienced - Disputes about tax assessments/payments/refunds"
label var q23_2_13_5 "Q23_2_13_5. Issues experienced - Difficulties getting someone to pay money they owe you (other than as a landlord)"
label var q23_2_14_1 "Q23_2_14_1. Issues experienced - Loss of a job or issues with pay/wages or other benefits"
label var q23_2_14_2 "Q23_2_14_2. Issues experienced - Exposure to health and safety risks"
label var q23_2_14_3 "Q23_2_14_3. Issues experienced - Conflicts with employer or other employees including discrimination and harassment"
label var q23_2_14_4 "Q23_2_14_4. Issues experienced - Other employment-related disputes"
label var q23_3_01_1 "Q23_3_1_1. Frequency experienced - Including issues with buying or selling property and disputes over title or ownership boundary locations and rights of way and Land Registry matters"
label var q23_3_02_1 "Q23_3_2_1. Frequency experienced - Disputes about maintenance including of boundaries trees gardens"
label var q23_3_02_2 "Q23_3_2_2. Frequency experienced - Problems or disputes to do with noise animals or unpleasant behaviour"
label var q23_3_02_3 "Q23_3_2_3. Frequency experienced - Other disputes with neighbours such as issues with parking"
label var q23_3_03_1 "Q23_3_3_1. Frequency experienced - Problems or disputes with your landlord over your rent or return of deposit"
label var q23_3_03_2 "Q23_3_3_2. Frequency experienced - Problem with your landlord about the condition of your accommodation including damage/repairs"
label var q23_3_03_3 "Q23_3_3_3. Frequency experienced - Eviction or threats of eviction or other harassment by a landlord"
label var q23_3_04_1 "Q23_3_4_1. Frequency experienced - Issues with a tenant such as delayed/no payment of rent or dispute over a deposit"
label var q23_3_04_2 "Q23_3_4_2. Frequency experienced - Property-related issues such as damage by tenants or access to property"
label var q23_3_04_3 "Q23_3_4_3. Frequency experienced - Issues with tenants such as evictions or complaints"
label var q23_3_05_1 "Q23_3_5_1. Frequency experienced - Building/planning related disputes"
label var q23_3_05_2 "Q23_3_5_2. Frequency experienced - Issues with builders/tradespeople about the quality of construction or repairs or disputes about costs"
label var q23_3_05_3 "Q23_3_5_3. Frequency experienced - Disputes about communal repairs/maintenance/costs"
label var q23_3_05_4 "Q23_3_5_4. Frequency experienced - Problems or disputes concerning Local Property Tax or Council/local services"
label var q23_3_05_5 "Q23_3_5_5. Frequency experienced - Squatters"
label var q23_3_05_6 "Q23_3_5_6. Frequency experienced - Dispute with utilities/essential services (e.g. waste disposal water electricity internet or other utility provider)"
label var q23_3_05_7 "Q23_3_5_7. Frequency experienced - Mortgage related issues including repossession threatened repossession or late payment"
label var q23_3_06_1 "Q23_3_6_1. Frequency experienced - Separation and/or divorce"
label var q23_3_06_2 "Q23_3_6_2. Frequency experienced - Violent or controlling behaviour by a current or former partner"
label var q23_3_06_3 "Q23_3_6_3. Frequency experienced - Violent or controlling behaviour by another family member"
label var q23_3_06_4 "Q23_3_6_4. Frequency experienced - Issues related to child access custody or child/spousal maintenance"
label var q23_3_06_5 "Q23_3_6_5. Frequency experienced - Problems or disputes related to elderly or other dependent adult care"
label var q23_3_06_6 "Q23_3_6_6. Frequency experienced - Disputes related to inheritance or a will"
label var q23_3_07_1 "Q23_3_7_1. Frequency experienced - Issues obtaining or with an Irish visa or residence card renewal"
label var q23_3_07_2 "Q23_3_7_2. Frequency experienced - Issues seeking international protection subsidiary protection or permission to remain"
label var q23_3_07_3 "Q23_3_7_3. Frequency experienced - Issues with an overseas visa / EU residence / emigration"
label var q23_3_07_4 "Q23_3_7_4. Frequency experienced - Issues applying for Irish naturalisation/citizenship"
label var q23_3_07_5 "Q23_3_7_5. Frequency experienced - Other citizenship or migration related issue"
label var q23_3_08_1 "Q23_3_8_1. Frequency experienced - A road traffic accident in which you were injured caused or made worse by someone else"
label var q23_3_08_2 "Q23_3_8_2. Frequency experienced - A road traffic accident in which someone else was injured that you caused or made worse"
label var q23_3_08_3 "Q23_3_8_3. Frequency experienced - Work-related accident"
label var q23_3_08_4 "Q23_3_8_4. Frequency experienced - Wrong or negligent medical treatment"
label var q23_3_08_5 "Q23_3_8_5. Frequency experienced - Other injury or illness caused or worsened by someone else"
label var q23_3_09_1 "Q23_3_9_1. Frequency experienced - Issues with jobseekers benefit or jobseekers allowance"
label var q23_3_09_2 "Q23_3_9_2. Frequency experienced - Issues related to maternity/parental government benefit"
label var q23_3_09_3 "Q23_3_9_3. Frequency experienced - Issues related to the State pension"
label var q23_3_09_4 "Q23_3_9_4. Frequency experienced - Issues with education-related grants (e.g. student grant scheme)"
label var q23_3_09_5 "Q23_3_9_5. Frequency experienced - Issues with Disability Allowance"
label var q23_3_09_6 "Q23_3_9_6. Frequency experienced - Other government benefit/payment issues"
label var q23_3_10_1 "Q23_3_10_1. Frequency experienced - Issues obtaining an Irish Passport other ID licences or other official documents"
label var q23_3_10_2 "Q23_3_10_2. Frequency experienced - Issues with obtaining healthcare or disability services"
label var q23_3_10_3 "Q23_3_10_3. Frequency experienced - Issues with obtaining government/social housing (excluding issues experienced as a tenant)"
label var q23_3_10_4 "Q23_3_10_4. Frequency experienced - Issues with obtaining education"
label var q23_3_11_1 "Q23_3_11_1. Frequency experienced - Product/purchases not delivered or significantly delayed"
label var q23_3_11_2 "Q23_3_11_2. Frequency experienced - Difficulty getting refunds repairs or replacements for products that were faulty damaged or not as described"
label var q23_3_12_1 "Q23_3_12_1. Frequency experienced - Issues with over-charging or hidden or unexpected fees"
label var q23_3_12_2 "Q23_3_12_2. Frequency experienced - Issues with quality of services or other service-related disputes"
label var q23_3_13_1 "Q23_3_13_1. Frequency experienced - Unable to pay bills/loans/debts including buy-now-pay-later (excluding mortgage and rental payments)"
label var q23_3_13_2 "Q23_3_13_2. Frequency experienced - Disputes about insurance coverage/claim"
label var q23_3_13_3 "Q23_3_13_3. Frequency experienced - Disputes with the bank or other financial institutions including refusal of credit/loan/mortgage"
label var q23_3_13_4 "Q23_3_13_4. Frequency experienced - Disputes about tax assessments/payments/refunds"
label var q23_3_13_5 "Q23_3_13_5. Frequency experienced - Difficulties getting someone to pay money they owe you (other than as a landlord)"
label var q23_3_14_1 "Q23_3_14_1. Frequency experienced - Loss of a job or issues with pay/wages or other benefits"
label var q23_3_14_2 "Q23_3_14_2. Frequency experienced - Exposure to health and safety risks"
label var q23_3_14_3 "Q23_3_14_3. Frequency experienced - Conflicts with employer or other employees including discrimination and harassment"
label var q23_3_14_4 "Q23_3_14_4. Frequency experienced - Other employment-related disputes"
label var q23_2_catselected "Q23_2. Categorization Selected"
label var q23_4_01_1 "Q23_4_1_1. Issue ranking - Including issues with buying or selling property and disputes over title or ownership boundary locations and rights of way and Land Registry matters"
label var q23_4_02_1 "Q23_4_2_1. Issue ranking - Disputes about maintenance including of boundaries trees gardens"
label var q23_4_02_2 "Q23_4_2_2. Issue ranking - Problems or disputes to do with noise animals or unpleasant behaviour"
label var q23_4_02_3 "Q23_4_2_3. Issue ranking - Other disputes with neighbours such as issues with parking"
label var q23_4_03_1 "Q23_4_3_1. Issue ranking - Problems or disputes with your landlord over your rent or return of deposit"
label var q23_4_03_2 "Q23_4_3_2. Issue ranking - Problem with your landlord about the condition of your accommodation including damage/repairs"
label var q23_4_03_3 "Q23_4_3_3. Issue ranking - Eviction or threats of eviction or other harassment by a landlord"
label var q23_4_04_1 "Q23_4_4_1. Issue ranking - Issues with a tenant such as delayed/no payment of rent or dispute over a deposit"
label var q23_4_04_2 "Q23_4_4_2. Issue ranking - Property-related issues such as damage by tenants or access to property"
label var q23_4_04_3 "Q23_4_4_3. Issue ranking - Issues with tenants such as evictions or complaints"
label var q23_4_05_1 "Q23_4_5_1. Issue ranking - Building/planning related disputes"
label var q23_4_05_2 "Q23_4_5_2. Issue ranking - Issues with builders/tradespeople about the quality of construction or repairs or disputes about costs"
label var q23_4_05_3 "Q23_4_5_3. Issue ranking - Disputes about communal repairs/maintenance/costs"
label var q23_4_05_4 "Q23_4_5_4. Issue ranking - Problems or disputes concerning Local Property Tax or Council/local services"
label var q23_4_05_5 "Q23_4_5_5. Issue ranking - Squatters"
label var q23_4_05_6 "Q23_4_5_6. Issue ranking - Dispute with utilities/essential services (e.g. waste disposal water electricity internet or other utility provider)"
label var q23_4_05_7 "Q23_4_5_7. Issue ranking - Mortgage related issues including repossession threatened repossession or late payment"
label var q23_4_06_1 "Q23_4_6_1. Issue ranking - Separation and/or divorce"
label var q23_4_06_2 "Q23_4_6_2. Issue ranking - Violent or controlling behaviour by a current or former partner"
label var q23_4_06_3 "Q23_4_6_3. Issue ranking - Violent or controlling behaviour by another family member"
label var q23_4_06_4 "Q23_4_6_4. Issue ranking - Issues related to child access custody or child/spousal maintenance"
label var q23_4_06_5 "Q23_4_6_5. Issue ranking - Problems or disputes related to elderly or other dependent adult care"
label var q23_4_06_6 "Q23_4_6_6. Issue ranking - Disputes related to inheritance or a will"
label var q23_4_07_1 "Q23_4_7_1. Issue ranking - Issues obtaining or with an Irish visa or residence card renewal"
label var q23_4_07_2 "Q23_4_7_2. Issue ranking - Issues seeking international protection subsidiary protection or permission to remain"
label var q23_4_07_3 "Q23_4_7_3. Issue ranking - Issues with an overseas visa / EU residence / emigration"
label var q23_4_07_4 "Q23_4_7_4. Issue ranking - Issues applying for Irish naturalisation/citizenship"
label var q23_4_07_5 "Q23_4_7_5. Issue ranking - Other citizenship or migration related issue"
label var q23_4_08_1 "Q23_4_8_1. Issue ranking - A road traffic accident in which you were injured caused or made worse by someone else"
label var q23_4_08_2 "Q23_4_8_2. Issue ranking - A road traffic accident in which someone else was injured that you caused or made worse"
label var q23_4_08_3 "Q23_4_8_3. Issue ranking - Work-related accident"
label var q23_4_08_4 "Q23_4_8_4. Issue ranking - Wrong or negligent medical treatment"
label var q23_4_08_5 "Q23_4_8_5. Issue ranking - Other injury or illness caused or worsened by someone else"
label var q23_4_09_1 "Q23_4_9_1. Issue ranking - Issues with jobseekers benefit or jobseekers allowance"
label var q23_4_09_2 "Q23_4_9_2. Issue ranking - Issues related to maternity/parental government benefit"
label var q23_4_09_3 "Q23_4_9_3. Issue ranking - Issues related to the State pension"
label var q23_4_09_4 "Q23_4_9_4. Issue ranking - Issues with education-related grants (e.g. student grant scheme)"
label var q23_4_09_5 "Q23_4_9_5. Issue ranking - Issues with Disability Allowance"
label var q23_4_09_6 "Q23_4_9_6. Issue ranking - Other government benefit/payment issues"
label var q23_4_10_1 "Q23_4_10_1. Issue ranking - Issues obtaining an Irish Passport other ID licences or other official documents"
label var q23_4_10_2 "Q23_4_10_2. Issue ranking - Issues with obtaining healthcare or disability services"
label var q23_4_10_3 "Q23_4_10_3. Issue ranking - Issues with obtaining government/social housing (excluding issues experienced as a tenant)"
label var q23_4_10_4 "Q23_4_10_4. Issue ranking - Issues with obtaining education"
label var q23_4_11_1 "Q23_4_11_1. Issue ranking - Product/purchases not delivered or significantly delayed"
label var q23_4_11_2 "Q23_4_11_2. Issue ranking - Difficulty getting refunds repairs or replacements for products that were faulty damaged or not as described"
label var q23_4_12_1 "Q23_4_12_1. Issue ranking - Issues with over-charging or hidden or unexpected fees"
label var q23_4_12_2 "Q23_4_12_2. Issue ranking - Issues with quality of services or other service-related disputes"
label var q23_4_13_1 "Q23_4_13_1. Issue ranking - Unable to pay bills/loans/debts including buy-now-pay-later (excluding mortgage and rental payments)"
label var q23_4_13_2 "Q23_4_13_2. Issue ranking - Disputes about insurance coverage/claim"
label var q23_4_13_3 "Q23_4_13_3. Issue ranking - Disputes with the bank or other financial institutions including refusal of credit/loan/mortgage"
label var q23_4_13_4 "Q23_4_13_4. Issue ranking - Disputes about tax assessments/payments/refunds"
label var q23_4_13_5 "Q23_4_13_5. Issue ranking - Difficulties getting someone to pay money they owe you (other than as a landlord)"
label var q23_4_14_1 "Q23_4_14_1. Issue ranking - Loss of a job or issues with pay/wages or other benefits"
label var q23_4_14_2 "Q23_4_14_2. Issue ranking - Exposure to health and safety risks"
label var q23_4_14_3 "Q23_4_14_3. Issue ranking - Conflicts with employer or other employees including discrimination and harassment"
label var q23_4_14_4 "Q23_4_14_4. Issue ranking - Other employment-related disputes"
label var q23_4_recentissue_selected "Q23_4. Recent Issue Selected"
label var q24 "Q24. Is this issue still ongoing or is it done with, either because it is resolved or because you, and anyone else, have given up trying to resolve it?"
label var q24_1_1 "Q24_1. Which of the following describes the current status of the issue? - A formal legal process is ongoing (e.g. at a court or tribunal)"
label var q24_1_2 "Q24_1. Which of the following describes the current status of the issue? - Another dispute resolution process outside a court or a tribunal is ongoing"
label var q24_1_3 "Q24_1. Which of the following describes the current status of the issue? - There is no dispute resolution process ongoing, but I am actively seeking advice or support to resolve or finish it"
label var q24_1_4 "Q24_1. Which of the following describes the current status of the issue? - I have not taken recent action as I am waiting for the other party to act or respond"
label var q24_1_5 "Q24_1. Which of the following describes the current status of the issue? - No recent action has been taken, but I still intend to resolve it"
label var q24_1_6 "Q24_1. Which of the following describes the current status of the issue? - No recent action has been taken"
label var q24_1_7 "Q24_1. Which of the following describes the current status of the issue? - Other, please specify:"
label var q24_1_8 "Q24_1. Which of the following describes the current status of the issue? - Don't know"
label var q24_1_9 "Q24_1. Which of the following describes the current status of the issue? - Prefer not to say"
label var q25_1_01 "Q25_1. Help sought - A court (small claims court, District Court, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var q25_1_02 "Q25_1. Help sought - A tribunal (e.g. International Protection Appeals Tribunal, Workplace Relations Commission, Social Welfare Appeals Office,"
label var q25_1_03 "Q25_1. Help sought - An Ombudsman (e.g. Financial Services Ombudsman)"
label var q25_1_04 "Q25_1. Help sought - The Gardai/police (or other law-enforcement)"
label var q25_1_05 "Q25_1. Help sought - Family Mediation Service"
label var q25_1_06 "Q25_1. Help sought - Another mediation, conciliation or other complaint or dispute resolution service (including online or commercial services)"
label var q25_1_07 "Q25_1. Help sought - A private solicitor or person working in a solicitor's office"
label var q25_1_08 "Q25_1. Help sought - A private barrister or person working in a barrister's office"
label var q25_1_09 "Q25_1. Help sought - A Legal Aid Board Law Centre"
label var q25_1_10 "Q25_1. Help sought - Another law centre such as the Free Legal Advice Centres"
label var q25_1_11 "Q25_1. Help sought - A government department, local council or government agency (e.g. a Housing or Social Welfare officer)"
label var q25_1_12 "Q25_1. Help sought - A non-legal professional, organisation or help line (e.g. Citizens Information Centre, Citizens Information Phone Centre,"
label var q25_1_13 "Q25_1. Help sought - Other person of standing in the local community (e.g. a politician, teacher, councillor, TDs or senator)"
label var q25_1_14 "Q25_1. Help sought - Online search (e.g. Google)"
label var q25_1_15 "Q25_1. Help sought - Social media (e.g. Facebook, X, Tik Tok, Reddit, Quora, Instagram)"
label var q25_1_16 "Q25_1. Help sought - AI tools (e.g. ChatGPT, Gemini or other ChatBot)"
label var q25_1_17 "Q25_1. Help sought - Another person (e.g. a friend, family member, or acquaintance [not a professional])"
label var q25_7_01 "Q25_7. How helpful were each of the following? - A court"
label var q25_7_02 "Q25_7. How helpful were each of the following? - A tribunal"
label var q25_7_03 "Q25_7. How helpful were each of the following? - An Ombudsman"
label var q25_7_04 "Q25_7. How helpful were each of the following? - The Gardai/police"
label var q25_7_05 "Q25_7. How helpful were each of the following? - Family Mediation Service"
label var q25_7_06 "Q25_7. How helpful were each of the following? - Another mediation, conciliation or other complaint or dispute resolution service"
label var q25_7_07 "Q25_7. How helpful were each of the following? - A private solicitor or person working in a solicitor's office"
label var q25_7_08 "Q25_7. How helpful were each of the following? - A private barrister or person working in a barrister's office"
label var q25_7_09 "Q25_7. How helpful were each of the following? - A Legal Aid Board Law Centre"
label var q25_7_10 "Q25_7. How helpful were each of the following? - Another law centre such as the Free Legal Advice Centres"
label var q25_7_11 "Q25_7. How helpful were each of the following? - A government department, local council or government agency"
label var q25_7_12 "Q25_7. How helpful were each of the following? - A non-legal professional, organisation or help line"
label var q25_7_13 "Q25_7. How helpful were each of the following? - Other person of standing in the local community"
label var q25_7_14 "Q25_7. How helpful were each of the following? - Online search"
label var q25_7_15 "Q25_7. How helpful were each of the following? - Social media"
label var q25_7_16 "Q25_7. How helpful were each of the following? - AI tools"
label var q25_7_17 "Q25_7. How helpful were each of the following? - Another person"
label var q25_3_01 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - There was no real disagreement or problem"
label var q25_3_02 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I felt the other person or organisation was in the right"
label var q25_3_03 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - The issue resolved itself without needing help"
label var q25_3_04 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I got all the help I needed from other organisations/people"
label var q25_3_05 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I didn't feel I needed help"
label var q25_3_06 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I didn't think the issue was serious enough"
label var q25_3_07 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I was concerned about how much time it would take"
label var q25_3_08 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I was concerned about how much it would cost"
label var q25_3_09 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - It was difficult to find someone nearby who could help me"
label var q25_3_10 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I thought it would be too stressful"
label var q25_3_11 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I was afraid it would damage my relationship with the other person or organisation"
label var q25_3_12 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I was scared to take action or ask for help"
label var q25_3_13 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I didn't know where or how to find information or advice"
label var q25_3_14 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I didn't think it would change the outcome"
label var q25_3_15 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - I had tried seeking help before and it wasn't helpful"
label var q25_3_16 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - Someone told me not to get advice or information"
label var q25_3_17 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - Other reason, please specify:"
label var q25_3_18 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - Don't know"
label var q25_3_19 "Q25_3. What was the reason you didn't obtain assistance from an organisation or professional to help you better understand the issue? - Prefer not to say"
label var q25_5 "Q25_5. Just to check, have you done / did you do anything, or do you expect to do anything to resolve or end this issue, such as talking to the other party?"
label var q25_6_01 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - It wasn't very important"
label var q25_6_02 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - It was resolved quickly"
label var q25_6_03 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - It would take too long"
label var q25_6_04 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - It would be too stressful"
label var q25_6_05 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - It would cost too much"
label var q25_6_06 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - It would damage the relationship with the other side"
label var q25_6_07 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - It would make you uncomfortable/ you were too ashamed or embarrassed to ask for help"
label var q25_6_08 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - It would make no difference"
label var q25_6_09 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - You had bigger issues"
label var q25_6_10 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - You were at fault or there was no dispute"
label var q25_6_11 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - You didn't know what to do"
label var q25_6_12 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - You didn't need information or advice"
label var q25_6_13 "Q25_6. For which of the following reasons, if any, haven't you done / didn't you do anything to try to resolve the issue? - Other reason (please specify)"
label var q26_01 "Q26. Issue resolved - A court (small claims court, District Circuit, High Court, Court of Appeal, Supreme Court, Europe etc)"
label var q26_02 "Q26. Issue resolved - A tribunal (e.g. international protection appeals tribunal - IPAT, Workplace Relations Commission, Social Welfare Appeals Office,"
label var q26_03 "Q26. Issue resolved - An Ombudsman (e.g. Financial Services Ombudsman)"
label var q26_04 "Q26. Issue resolved - The Gardai/police (or other law-enforcement)"
label var q26_05 "Q26. Issue resolved - A formal mediation, conciliation or other complaint or dispute resolution service (including Family Mediation Service)"
label var q26_06 "Q26. Issue resolved - A lawyer, or person working in a lawyer's office"
label var q26_07 "Q26. Issue resolved - A government department, local council or government agency or a person within them appointed to make decisions (e.g. a Housing or Social Welfare officer)"
label var q26_08 "Q26. Issue resolved - A community leader, or other person of standing (e.g. a politician, teacher, councillor, TDs or senator, or priest)"
label var q26_09 "Q26. Issue resolved - Other dispute resolution service, including online and commercial services"
label var q26_10 "Q26. Issue resolved - Other person (e.g. a friend, family member, or acquaintance not in a professional capacity)"
label var q26_11 "Q26. Issue resolved - Other professional or organisation"
label var q27_01 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - The issue is/was not important enough"
label var q27_02 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - The issue resolved so I didn't need to"
label var q27_03 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - I was/am confident that I could/can easily resolve it by myself"
label var q27_04 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - I was/am confident that I could/can easily resolve it with the help I got/am getting"
label var q27_05 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - Up to the other party to take this action"
label var q27_06 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - I caused the issue"
label var q27_07 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - I did not know where to go"
label var q27_08 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - I could not obtain legal assistance"
label var q27_09 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - It was too expensive / I was fearful of what it could cost"
label var q27_10 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - It was too far away or hard to reach"
label var q27_11 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - It was too inconvenient"
label var q27_12 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - I did not trust the authorities"
label var q27_13 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - I did not think they could help"
label var q27_14 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - I was afraid of the consequences for me/my family"
label var q27_15 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - I did not know it was possible to turn somewhere to resolve the issue"
label var q27_16 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - Other reason:"
label var q27_17 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - Don't know"
label var q27_18 "Q27. What was the reason you have not turned / did not turn to a professional or organisation to resolve the issue? - Prefer not to say"
label var q29_1_it01_a "Q29_1_iter01_a. Agree or Disagree - A court - Both parties had the same opportunity to explain their position"
label var q29_1_it01_b "Q29_1_iter01_b. Agree or Disagree - A court - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it01_c "Q29_1_iter01_c. Agree or Disagree - A court - The process was efficient"
label var q29_1_it01_d "Q29_1_iter01_d. Agree or Disagree - A court - The process was affordable"
label var q29_1_it01_e "Q29_1_iter01_e. Agree or Disagree - A court - The duration/length of the process was reasonable"
label var q29_1_it01_f "Q29_1_iter01_f. Agree or Disagree - A court - The process was fair"
label var q29_1_it01_g "Q29_1_iter01_g. Agree or Disagree - A court - The outcome was fair"
label var q29_1_it01_h "Q29_1_iter01_h. Agree or Disagree - A court - <> was helpful"
label var q29_1_it01_i "Q29_1_iter01_i. Agree or Disagree - A court - <> took my concerns and experiences seriously"
label var q29_1_it02_a "Q29_1_iter02_a. Agree or Disagree - A tribunal - Both parties had the same opportunity to explain their position"
label var q29_1_it02_b "Q29_1_iter02_b. Agree or Disagree - A tribunal - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it02_c "Q29_1_iter02_c. Agree or Disagree - A tribunal - The process was efficient"
label var q29_1_it02_d "Q29_1_iter02_d. Agree or Disagree - A tribunal - The process was affordable"
label var q29_1_it02_e "Q29_1_iter02_e. Agree or Disagree - A tribunal - The duration/length of the process was reasonable"
label var q29_1_it02_f "Q29_1_iter02_f. Agree or Disagree - A tribunal - The process was fair"
label var q29_1_it02_g "Q29_1_iter02_g. Agree or Disagree - A tribunal - The outcome was fair"
label var q29_1_it02_h "Q29_1_iter02_h. Agree or Disagree - A tribunal - <> was helpful"
label var q29_1_it02_i "Q29_1_iter02_i. Agree or Disagree - A tribunal - <> took my concerns and experiences seriously"
label var q29_1_it03_a "Q29_1_iter03_a. Agree or Disagree - An Ombudsman - Both parties had the same opportunity to explain their position"
label var q29_1_it03_b "Q29_1_iter03_b. Agree or Disagree - An Ombudsman - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it03_c "Q29_1_iter03_c. Agree or Disagree - An Ombudsman - The process was efficient"
label var q29_1_it03_d "Q29_1_iter03_d. Agree or Disagree - An Ombudsman - The process was affordable"
label var q29_1_it03_e "Q29_1_iter03_e. Agree or Disagree - An Ombudsman - The duration/length of the process was reasonable"
label var q29_1_it03_f "Q29_1_iter03_f. Agree or Disagree - An Ombudsman - The process was fair"
label var q29_1_it03_g "Q29_1_iter03_g. Agree or Disagree - An Ombudsman - The outcome was fair"
label var q29_1_it03_h "Q29_1_iter03_h. Agree or Disagree - An Ombudsman - <> was helpful"
label var q29_1_it03_i "Q29_1_iter03_i. Agree or Disagree - An Ombudsman - <> took my concerns and experiences seriously"
label var q29_1_it04_a "Q29_1_iter04_a. Agree or Disagree - The Gardai/police - Both parties had the same opportunity to explain their position"
label var q29_1_it04_b "Q29_1_iter04_b. Agree or Disagree - The Gardai/police - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it04_c "Q29_1_iter04_c. Agree or Disagree - The Gardai/police - The process was efficient"
label var q29_1_it04_d "Q29_1_iter04_d. Agree or Disagree - The Gardai/police - The process was affordable"
label var q29_1_it04_e "Q29_1_iter04_e. Agree or Disagree - The Gardai/police - The duration/length of the process was reasonable"
label var q29_1_it04_f "Q29_1_iter04_f. Agree or Disagree - The Gardai/police - The process was fair"
label var q29_1_it04_g "Q29_1_iter04_g. Agree or Disagree - The Gardai/police - The outcome was fair"
label var q29_1_it04_h "Q29_1_iter04_h. Agree or Disagree - The Gardai/police - <> was helpful"
label var q29_1_it04_i "Q29_1_iter04_i. Agree or Disagree - The Gardai/police - <> took my concerns and experiences seriously"
label var q29_1_it05_a "Q29_1_iter05_a. Agree or Disagree - A formal mediation service - Both parties had the same opportunity to explain their position"
label var q29_1_it05_b "Q29_1_iter05_b. Agree or Disagree - A formal mediation service - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it05_c "Q29_1_iter05_c. Agree or Disagree - A formal mediation service - The process was efficient"
label var q29_1_it05_d "Q29_1_iter05_d. Agree or Disagree - A formal mediation service - The process was affordable"
label var q29_1_it05_e "Q29_1_iter05_e. Agree or Disagree - A formal mediation service - The duration/length of the process was reasonable"
label var q29_1_it05_f "Q29_1_iter05_f. Agree or Disagree - A formal mediation service - The process was fair"
label var q29_1_it05_g "Q29_1_iter05_g. Agree or Disagree - A formal mediation service - The outcome was fair"
label var q29_1_it05_h "Q29_1_iter05_h. Agree or Disagree - A formal mediation service - <> was helpful"
label var q29_1_it05_i "Q29_1_iter05_i. Agree or Disagree - A formal mediation service - <> took my concerns and experiences seriously"
label var q29_1_it06_a "Q29_1_iter06_a. Agree or Disagree - A lawyer / lawyer's office - Both parties had the same opportunity to explain their position"
label var q29_1_it06_b "Q29_1_iter06_b. Agree or Disagree - A lawyer / lawyer's office - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it06_c "Q29_1_iter06_c. Agree or Disagree - A lawyer / lawyer's office - The process was efficient"
label var q29_1_it06_d "Q29_1_iter06_d. Agree or Disagree - A lawyer / lawyer's office - The process was affordable"
label var q29_1_it06_e "Q29_1_iter06_e. Agree or Disagree - A lawyer / lawyer's office - The duration/length of the process was reasonable"
label var q29_1_it06_f "Q29_1_iter06_f. Agree or Disagree - A lawyer / lawyer's office - The process was fair"
label var q29_1_it06_g "Q29_1_iter06_g. Agree or Disagree - A lawyer / lawyer's office - The outcome was fair"
label var q29_1_it06_h "Q29_1_iter06_h. Agree or Disagree - A lawyer / lawyer's office - <> was helpful"
label var q29_1_it06_i "Q29_1_iter06_i. Agree or Disagree - A lawyer / lawyer's office - <> took my concerns and experiences seriously"
label var q29_1_it07_a "Q29_1_iter07_a. Agree or Disagree - A government department, local council or government agency - Both parties had the same opportunity to explain their position"
label var q29_1_it07_b "Q29_1_iter07_b. Agree or Disagree - A government department, local council or government agency - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it07_c "Q29_1_iter07_c. Agree or Disagree - A government department, local council or government agency - The process was efficient"
label var q29_1_it07_d "Q29_1_iter07_d. Agree or Disagree - A government department, local council or government agency - The process was affordable"
label var q29_1_it07_e "Q29_1_iter07_e. Agree or Disagree - A government department, local council or government agency - The duration/length of the process was reasonable"
label var q29_1_it07_f "Q29_1_iter07_f. Agree or Disagree - A government department, local council or government agency - The process was fair"
label var q29_1_it07_g "Q29_1_iter07_g. Agree or Disagree - A government department, local council or government agency - The outcome was fair"
label var q29_1_it07_h "Q29_1_iter07_h. Agree or Disagree - A government department, local council or government agency - <> was helpful"
label var q29_1_it07_i "Q29_1_iter07_i. Agree or Disagree - A government department, local council or government agency - <> took my concerns and experiences seriously"
label var q29_1_it08_a "Q29_1_iter08_a. Agree or Disagree - A community leader, or other person of standing - Both parties had the same opportunity to explain their position"
label var q29_1_it08_b "Q29_1_iter08_b. Agree or Disagree - A community leader, or other person of standing - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it08_c "Q29_1_iter08_c. Agree or Disagree - A community leader, or other person of standing - The process was efficient"
label var q29_1_it08_d "Q29_1_iter08_d. Agree or Disagree - A community leader, or other person of standing - The process was affordable"
label var q29_1_it08_e "Q29_1_iter08_e. Agree or Disagree - A community leader, or other person of standing - The duration/length of the process was reasonable"
label var q29_1_it08_f "Q29_1_iter08_f. Agree or Disagree - A community leader, or other person of standing - The process was fair"
label var q29_1_it08_g "Q29_1_iter08_g. Agree or Disagree - A community leader, or other person of standing - The outcome was fair"
label var q29_1_it08_h "Q29_1_iter08_h. Agree or Disagree - A community leader, or other person of standing - <> was helpful"
label var q29_1_it08_i "Q29_1_iter08_i. Agree or Disagree - A community leader, or other person of standing - <> took my concerns and experiences seriously"
label var q29_1_it09_a "Q29_1_iter09_a. Agree or Disagree - Other dispute resolution service - Both parties had the same opportunity to explain their position"
label var q29_1_it09_b "Q29_1_iter09_b. Agree or Disagree - Other dispute resolution service - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it09_c "Q29_1_iter09_c. Agree or Disagree - Other dispute resolution service - The process was efficient"
label var q29_1_it09_d "Q29_1_iter09_d. Agree or Disagree - Other dispute resolution service - The process was affordable"
label var q29_1_it09_e "Q29_1_iter09_e. Agree or Disagree - Other dispute resolution service - The duration/length of the process was reasonable"
label var q29_1_it09_f "Q29_1_iter09_f. Agree or Disagree - Other dispute resolution service - The process was fair"
label var q29_1_it09_g "Q29_1_iter09_g. Agree or Disagree - Other dispute resolution service - The outcome was fair"
label var q29_1_it09_h "Q29_1_iter09_h. Agree or Disagree - Other dispute resolution service - <> was helpful"
label var q29_1_it09_i "Q29_1_iter09_i. Agree or Disagree - Other dispute resolution service - <> took my concerns and experiences seriously"
label var q29_1_it11_a "Q29_1_iter11_a. Agree or Disagree - Other professional or organisation - Both parties had the same opportunity to explain their position"
label var q29_1_it11_b "Q29_1_iter11_b. Agree or Disagree - Other professional or organisation - The justification for the decision/outcome was clearly explained to me"
label var q29_1_it11_c "Q29_1_iter11_c. Agree or Disagree - Other professional or organisation - The process was efficient"
label var q29_1_it11_d "Q29_1_iter11_d. Agree or Disagree - Other professional or organisation - The process was affordable"
label var q29_1_it11_e "Q29_1_iter11_e. Agree or Disagree - Other professional or organisation - The duration/length of the process was reasonable"
label var q29_1_it11_f "Q29_1_iter11_f. Agree or Disagree - Other professional or organisation - The process was fair"
label var q29_1_it11_g "Q29_1_iter11_g. Agree or Disagree - Other professional or organisation - The outcome was fair"
label var q29_1_it11_h "Q29_1_iter11_h. Agree or Disagree - Other professional or organisation - <> was helpful"
label var q29_1_it11_i "Q29_1_iter11_i. Agree or Disagree - Other professional or organisation - <> took my concerns and experiences seriously"
label var q29_2_it01_a "Q29_2_iter01_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it01_b "Q29_2_iter01_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it01_c "Q29_2_iter01_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it01_d "Q29_2_iter01_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q29_2_it02_a "Q29_2_iter02_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it02_b "Q29_2_iter02_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it02_c "Q29_2_iter02_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it02_d "Q29_2_iter02_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q29_2_it03_a "Q29_2_iter03_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it03_b "Q29_2_iter03_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it03_c "Q29_2_iter03_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it03_d "Q29_2_iter03_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q29_2_it04_a "Q29_2_iter04_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it04_b "Q29_2_iter04_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it04_c "Q29_2_iter04_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it04_d "Q29_2_iter04_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q29_2_it05_a "Q29_2_iter05_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it05_b "Q29_2_iter05_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it05_c "Q29_2_iter05_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it05_d "Q29_2_iter05_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q29_2_it06_a "Q29_2_iter06_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it06_b "Q29_2_iter06_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it06_c "Q29_2_iter06_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it06_d "Q29_2_iter06_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q29_2_it07_a "Q29_2_iter07_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it07_b "Q29_2_iter07_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it07_c "Q29_2_iter07_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it07_d "Q29_2_iter07_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q29_2_it08_a "Q29_2_iter08_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it08_b "Q29_2_iter08_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it08_c "Q29_2_iter08_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it08_d "Q29_2_iter08_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q29_2_it09_a "Q29_2_iter09_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it09_b "Q29_2_iter09_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it09_c "Q29_2_iter09_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it09_d "Q29_2_iter09_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q29_2_it11_a "Q29_2_iter11_a. Agree / disagree - I received the decision/outcome of the process in writing"
label var q29_2_it11_b "Q29_2_iter11_b. Agree / disagree - I could have appealed the decision/outcome"
label var q29_2_it11_c "Q29_2_iter11_c. Agree / disagree - I was represented by a lawyer"
label var q29_2_it11_d "Q29_2_iter11_d. Agree / disagree - I was represented by another advisor, person or organisation"
label var q28 "Q28. Which of the following best reflects how the issue resolution was brought about? Select the first that applies."
label var q30 "Q30. Regardless of the outcome of this issue, do you feel the process through which the outcome was reached was overall fair or unfair to everybody concerned?"
label var q31_1 "Q31. To what extent do you agree or disagree with the following statements about experiencing the issue? - I understood or came / have come to understand my rights and responsibilities"
label var q31_2 "Q31. To what extent do you agree or disagree with the following statements about experiencing the issue? - I knew / know where to get good information and advice about resolving issues"
label var q31_3 "Q31. To what extent do you agree or disagree with the following statements about experiencing the issue? - I was able / have been able to get all the expert help that I needed"
label var q31_4 "Q31. To what extent do you agree or disagree with the following statements about experiencing the issue? - I was / am confident I could achieve a fair outcome"
label var q32_1 "Q32_1. Overall, how much impact has experiencing this issue, or trying to deal with this issue, had on you?"
label var q32_01 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Health difficulties or injury"
label var q32_02 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Stress or emotional strain"
label var q32_03 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Damage to personal or family relationships"
label var q32_04 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Being threatened or feeling unsafe"
label var q32_05 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Damage to property"
label var q32_06 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Changes to your housing situation"
label var q32_07 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Loss of employment"
label var q32_08 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Loss of money"
label var q32_09 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Loss of confidence or fear"
label var q32_10 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Deterioration in mental health (e.g. anxiety, depression)"
label var q32_11 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Feeling isolated or loss of support networks"
label var q32_12 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Use of addictive substances (e.g. alcohol or drugs)"
label var q32_13 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Delay or disruption to education or training"
label var q32_14 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Delay or disruption in accessing public services (e.g. healthcare, social services)"
label var q32_15 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Finding everyday activities more difficult"
label var q32_16 "Q32. Did you experience any of the following because of, or from trying to deal with, this issue? - Feeling less trust in public institutions (e.g. justice system, police, government)"
label var q15 "Q15. Do you have any long-term health conditions that limit your ability to carry out everyday activities?"
label var q14 "Q14. What is your ethnic group/background?"
label var q06 "Q6. Are you an Irish citizen?"
label var q10 "Q10. Other than holidays or short visits abroad, since which year have you been living in the Republic of Ireland continuously?"
label var q05 "Q5. Which of the following best describes your current status?"
label var q19_1 "Q19_1. How many adults aged 18 or over (including yourself) live in your household?"
label var q19_2 "Q19_2. How many children aged under 18 live in your household, at least some of the time?"
label var q19_3 "Q19_3. Do any of the children that live in your household, sometimes live in another household?"
label var q20 "Q20. Approximately what is the total of your household income, from all sources including benefits, before tax?"
label var q03actual "Q3. Actual"
label var q10actual "Q10. Actual"
label var q19_1actual "Q19_1. Actual"
label var q19_2actual "Q19_2. Actual"
label var Q17_oth "Q17_oth"
label var Q24_1_oth "Q24_1_oth"
label var Q24_2_month "Q24_2_month"
label var Q24_2_year "Q24_2_year"
label var Q24_2_DKNA "Q24_2_DKNA"
label var Q24_3_month "Q24_3_month"
label var Q24_3_year "Q24_3_year"
label var Q24_3_DKNA "Q24_3_DKNA"
label var Q25_3_oth "Q25_3_oth"
label var Q25_4 "Q25_4. Please specify which organisations or people helped you"
label var Q25_5_3 "Q25_5_3. Have done something"
label var Q25_6_oth "Q25_6_oth"
label var Q27_oth "Q27_oth"
label var Q28_oth "Q28_oth"
label var Q34_1 "Q34_1. Can you name up to three organisations that you know provide free or affordable assistance for people facing issues?"
label var Q34_2 "Q34_2. Can you name up to three organisations that you know provide free or affordable assistance for people facing issues?"
label var Q34_3 "Q34_3. Can you name up to three organisations that you know provide free or affordable assistance for people facing issues?"
label var Q34_DKNA "Q34_DKNA"
label var Q14_4 "Q14_4. Any other White background"
label var Q14_7 "Q14_7. Any other Black background"
label var Q14_11 "Q14_11. Any other Asian background"
label var Q14_13 "Q14_13. Mixed group/background"
label var Q14_14 "Q14_14. Other group/background"
